name: lines per hour
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: gh api calls
        run: |
          echo "github.actor: ${{github.actor}}"
          echo "github.repository_owner: ${{github.actor}}"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh api \
            -H "Accept: application/vnd.github+json" \
            /user/orgs