name: lines per hour
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: list auth
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "github.actor: ${{github.actor}}"
          echo "github.repository_owner: ${{github.actor}}"
          gh api -X GET "users/${{github.actor}}/orgs" -F per_page=100 --paginate
          gh api \
            -H "Accept: application/vnd.github+json" \
            /users