name: lines per hour
on: push
jobs:
  build:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: gh api calls
        env:
          GITHUB_TOKEN: ${{secrets.PAT}}
        run: |
          echo "github.actor: ${{github.actor}}"
          echo "github.repository_owner: ${{github.actor}}"
          gh api \
            -H "Accept: application/vnd.github+json" \
            /user/orgs | jq '[.[].login] | {orgs: .}' > orgs.json
          export ORGS_JSON=orgs.json
          gh api \
            -H "Accept: application/vnd.github+json" \
            /users/${{github.actor}}/events > events.json
          cat events.json | \
            jq '.[] | select(.type=="PushEvent") | .payload.commits[]' | \
            jq -s '.' > commits.json
      - name: archive json
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            orgs.json
            events.json
            commits.json