name: lines per hour
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: list auth
        run: |
          echo "github.actor: ${{github.actor}}"
          echo "github.repository_owner: ${{github.actor}}"